"""
Darwin Multi-Agent System - Pull Request Model
==============================================
Represents GitHub Pull Requests created by the Engineer Agent.
"""

from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field

from .enums import PRStatus


class FileChange(BaseModel):
    """A file changed in the PR."""
    
    path: str = Field(..., description="File path")
    additions: int = Field(default=0, description="Lines added")
    deletions: int = Field(default=0, description="Lines removed")
    status: str = Field(default="modified", description="added, modified, removed")


class PullRequest(BaseModel):
    """
    A GitHub Pull Request created by the Engineer Agent.
    
    Created by: Engineer Agent
    Consumed by: Human reviewers
    """
    
    # Identity
    id: Optional[str] = Field(default=None, alias="_id", description="MongoDB ObjectId")
    task_id: str = Field(..., description="ID of the source task")
    ux_issue_id: str = Field(..., description="ID of the source UX issue")
    signal_id: Optional[str] = Field(default=None, description="ID of the original signal")
    
    # GitHub Details
    pr_number: int = Field(..., description="GitHub PR number")
    pr_url: str = Field(..., description="GitHub PR URL")
    branch_name: str = Field(..., description="Branch name (e.g., darwin/fix-rage-click-123)")
    base_branch: str = Field(default="main", description="Target branch")
    
    # PR Content
    title: str = Field(..., description="PR title")
    body: str = Field(..., description="PR body/description in markdown")
    
    # Changes
    files_changed: List[FileChange] = Field(default_factory=list, description="Files modified")
    total_additions: int = Field(default=0, description="Total lines added")
    total_deletions: int = Field(default=0, description="Total lines removed")
    
    # Status
    status: PRStatus = Field(default=PRStatus.OPEN, description="PR status")
    mergeable: Optional[bool] = Field(default=None, description="Can be merged")
    
    # Review
    reviewers: List[str] = Field(default_factory=list, description="Requested reviewers")
    review_comments: int = Field(default=0, description="Number of review comments")
    
    # Labels
    labels: List[str] = Field(
        default_factory=lambda: ["darwin-fix", "auto-generated"],
        description="PR labels"
    )
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow, description="PR creation time")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update")
    merged_at: Optional[datetime] = Field(default=None, description="When merged")
    closed_at: Optional[datetime] = Field(default=None, description="When closed")
    
    class Config:
        populate_by_name = True
        use_enum_values = True
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
    
    def to_mongo(self) -> dict:
        """Convert to MongoDB document format."""
        data = self.model_dump(by_alias=True, exclude_none=True)
        if "_id" in data and data["_id"] is None:
            del data["_id"]
        # Handle nested models
        if "files_changed" in data:
            data["files_changed"] = [dict(f) for f in data["files_changed"]]
        return data
    
    @classmethod
    def from_mongo(cls, doc: dict) -> "PullRequest":
        """Create from MongoDB document."""
        if "_id" in doc:
            doc["_id"] = str(doc["_id"])
        return cls(**doc)
    
    def generate_body(self, ux_issue: dict) -> str:
        """Generate PR body from UX issue data."""
        return f"""## 🧬 Darwin Auto-Fix

### Issue Summary
{ux_issue.get('title', 'UX Issue Fix')}

### Root Cause
{ux_issue.get('root_cause', 'See analysis below')}

### User Impact
{ux_issue.get('user_impact', 'Improved user experience')}

### Changes Made
{ux_issue.get('recommended_fix', {}).get('description', 'Code optimization')}

### Metrics
- **Affected Users:** {ux_issue.get('affected_users', 'N/A')}
- **Confidence:** {ux_issue.get('confidence', 0.8) * 100:.0f}%
- **Priority:** {ux_issue.get('priority', 'medium')}

---
*🤖 This PR was automatically generated by Darwin - AI Growth Engineer*
"""
